# Практическое задание 10. «Работа с табличными данными, Построение графиков»

**10.1[44]**: Дан код, генерирующий DataFrame, которая состоит всего из 1 столбца. Ваша задача перевести его в one hot вид.

Статья про one hot вид https://colab.research.google.com/drive/1qKamnDiRmpRZkpiqWPkunBdAhmzhMcGz?usp=sharing
- Сделайте one hot вид с использованием get_dummies
- Сделайте one hot вид с использованием изученных методов группировки данных. Обратите внимание, что Nan это не ноль.

In [38]:
import random

In [39]:
import pandas as pd

In [40]:
lst = ['robot'] * 10

In [41]:
lst += ['human'] * 10

In [42]:
random.shuffle(lst)

In [43]:
data = pd.DataFrame({'whoAmI':lst})

In [44]:
data.head()

  whoAmI
0  human
1  robot
2  human
3  human
4  robot

In [45]:
data

   whoAmI
0   human
1   robot
2   human
3   human
4   robot
5   robot
6   human
7   human
8   human
9   human
10  human
11  human
12  robot
13  human
14  robot
15  robot
16  robot
17  robot
18  robot
19  robot

In [46]:
pd.get_dummies(data['whoAmI'])

    human  robot
0       1      0
1       0      1
2       1      0
3       1      0
4       0      1
5       0      1
6       1      0
7       1      0
8       1      0
9       1      0
10      1      0
11      1      0
12      0      1
13      1      0
14      0      1
15      0      1
16      0      1
17      0      1
18      0      1
19      0      1

In [47]:
data.loc[data['whoAmI'] == 'human', 'human'] = '1'
data.loc[data['whoAmI'] == 'human', 'robot'] = '0'
data.loc[data['whoAmI'] == 'robot', 'robot'] = '1'
data.loc[data['whoAmI'] == 'robot', 'human'] = '0'

In [50]:
data.head()

  whoAmI human robot
0  human     1     0
1  robot     0     1
2  human     1     0
3  human     1     0
4  robot     0     1

In [48]:
data

   whoAmI human robot
0   human     1     0
1   robot     0     1
2   human     1     0
3   human     1     0
4   robot     0     1
5   robot     0     1
6   human     1     0
7   human     1     0
8   human     1     0
9   human     1     0
10  human     1     0
11  human     1     0
12  robot     0     1
13  human     1     0
14  robot     0     1
15  robot     0     1
16  robot     0     1
17  robot     0     1
18  robot     0     1
19  robot     0     1